[tool.flake8]
  max-line-length = 88
  extend-ignore = ["E203"]
  exclude = ["__init__.py"]

[tool.isort]
  force_single_line = true
  force_sort_within_sections = true
  include_trailing_comma = true
  multi_line_output = 3
  sort_order = "native"
  use_parentheses = true

[tool.coverage.report]
  exclude_lines = [
    "pragma: no cover",
    "raise NotImplementedError",
    "raise RuntimeError",
    "raise ValueError",
    "verbose",
    "warn_type",
    "warnings",
  ]

[tool.coverage.run]
  disable_warnings = [
    "couldnt-parse",
  ]

[tool.pytest.ini_options]
  filterwarnings = [
    "ignore:Casting complex values to real discards the imaginary part",
  ]
