name: package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
        pytorch-version: [1.11.0, 2.1.1]

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y libsndfile1
          pip3 install torch==${{ matrix.pytorch-version }}+cpu -f https://download.pytorch.org/whl/torch_stable.html

      - name: Install
        run: make dev tool

      - name: Check
        run: make check

      - name: Test
        run: make test

      - name: Coverage
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          verbose: true
