name: ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
        pytorch-version: [1.9.0, 1.11.0]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: install packages
        run: |
          sudo apt-get update -qq
          pip3 install torch==${{ matrix.pytorch-version }}+cpu -f https://download.pytorch.org/whl/torch_stable.html
      - name: install diffsptk
        run: make dev
      - name: make format
        run: make format
      - name: make test
        run: make test
